spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=UTC
    username: root
    password: YJzj0610&
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #password: 123456
      timeout: 5000

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  security:
    access:
      deniedHandler: com.example.douyin.exception.CustomAccessDeniedHandler
  web:
    resources:
      static-locations: classpath:/static, classpath:/
server:
  port: 8080


